### ISSUE TITLE
Allow non-UUID types on the primary key field

### ISSUE THREAD

**Issue by AlexITC** [wiringbits/wiringbits-webapp-utils#138]
Let's update [TableSettings](https://github.com/wiringbits/wiringbits-webapp-utils/blob/master/admin-data-explorer-play-server/src/main/scala/net/wiringbits/webapp/utils/admin/config/TableSettings.scala) model to include  new field; `primaryKeyDataType` which can be `UUID`/`Int`/`Long`/`String`, by default, it must be `UUID` to keep compatibility with our existing code.

When such data type is specified, we must be able to perform CRUD operations on such table by using the existing admin endpoints.

In order to test this, let's update the tests to define a new tables that are exposed by [DataExplorerTestModule](https://github.com/wiringbits/wiringbits-webapp-utils/blob/master/admin-data-explorer-play-server/src/test/scala/net/wiringbits/webapp/utils/admin/modules/DataExplorerTestModule.scala).

Tables:
```sql
CREATE TABLE uuid_table (
  id UUID NOT NULL PRIMARY KEY
);

CREATE TABLE int_table (
  id INT NOT NULL PRIMARY KEY
);

CREATE TABLE long_table (
  id BIGINT NOT NULL PRIMARY KEY
);

CREATE TABLE string_table (
  id TEXT NOT NULL PRIMARY KEY
);
```

Then, settings must be updated to be like:

```scala
  val settings: List[TableSettings] = List(
    TableSettings(tableName = "users", primaryKeyField = "user_id"), // defaults to UUID pk
    TableSettings(tableName = "uuid_table", primaryKeyField = "id", primaryKeyDataType = "UUID"),
    TableSettings(tableName = "int_table", primaryKeyField = "id", primaryKeyDataType = "Int"),
    TableSettings(tableName = "long_table", primaryKeyField = "id", primaryKeyDataType = "Long"),
    TableSettings(tableName = "string_table", primaryKeyField = "id", primaryKeyDataType = "String")
  )
```

Let's make sure that tests query all these tables.

**Comment by nickcoast** [comment]
Hi, I was looking at this yesterday.

Seems in `DatabaseTablesDAO.scala` you could add a `primaryKeyType` argument to:

- find
- create
- update
- delete

And then handle the different datatypes with a `match` expression. But… are they all passed as string to `preparedStatement.setObject()`?
Or does each type of key need to be cast to its correct data type, like you currently have with `UUID.fromString(primaryKeyValue)`

Could look like this:

```
def find(tableName: String, primaryKeyField: String, primaryKeyValue: String, primaryKeyType: String)(implicit
    conn: Connection
): Option[TableRow] = {
  val sql = s"""
  SELECT *
    FROM $tableName
  WHERE $primaryKeyField = ?
  """
  val preparedStatement = conn.prepareStatement(sql)
  val primaryKeyString = primaryKeyType match { // regular string unless UUID
    case "UUID" => preparedStatement.setObject(1, UUID.fromString(primaryKeyValue))
    case "Int" => preparedStatement.setInt(1,primaryKeyValue.toInt)
    case "Long" => preparedStatement.setLong(1,primaryKeyValue.toLong)
    case "String" => preparedStatement.setString(1,primaryKeyValue)
  }
  // TODO: UUID from String can fail if the ID field isn't an UUID
  // Done!! ?

  val resultSet = preparedStatement.executeQuery()
  Try {
    resultSet.next()
    val numberOfColumns = resultSet.getMetaData.getColumnCount
    val row = for {
      columnNumber <- 1 to numberOfColumns
      cellData = resultSet.getString(columnNumber)
    } yield Cell(Option(cellData).getOrElse(""))
    TableRow(row.toList)
  }.toOption
}
```

I have not actually tried that solution yet.


I made some other changes, though, and `AdminControllerSpec.scala` passed all tests, but as you mentioned, it's only testing the users table.

At the top:
`def usersSettings: TableSettings = dataExplorerSettings.tables.headOption.value`

That takes the first item from `DataExplorerTestModule.scala`, right?
`TableSettings("users", "user_id")`

So all the tests here run only on the `users` table, right? To test `uuid_table`, `int_table`, etc, I could do something like this:

```
def usersSettings: TableSettings = dataExplorerSettings.tables.headOption.value // current code
def uuidSettings: TableSettings = dataExplorerSettings.tables(1).value  // new
def intSettings: TableSettings = dataExplorerSettings.tables(2).value // new
```

And then add tests for each additional table. Seems like that would be a lot of duplicate code, but maybe that's the best way with unit testing?

Else modify the existing CRUD tests so they run once for each table?

**Comment by AlexITC** [comment]
> Seems in DatabaseTablesDAO.scala you could add a primaryKeyType argument to `find`/`create`/`update`/`delete`

- `find` does not seem to require the primary key type because everything gets converted to a string.
- `create` is more problematic because it auto-generates a `UUID` (see `preparedStatement.setObject(1, UUID.randomUUID())`), then, simpler way would be to assume that primary key is either `UUID`/`SERIAL`/`BIGSERIAL`, for the non-UUID cases, we'd need adapting `QueryBuilder.create(tableName, body, primaryKeyField)` to send the pk type, such sql generator needs to include the primary key field for UUID but exclude it for serial values, which affects the loop start index `for (i <- 2 to body.size + 1)`.
- `update` changes are very similar to the ones for the `create` operation.
- `delete` needs to check the primary key type to avoid converting the value to UUID when it is a SERIAL.

> And then handle the different datatypes with a match expression. But… are they all passed as string to preparedStatement.setObject()?
>  Or does each type of key need to be cast to its correct data type, like you currently have with UUID.fromString(primaryKeyValue)

I'm actually surprised by this but it seems that strings work fine, I'm now wondering whether the UUID conversion is necessary.

> Could look like this:

Indeed, but `find` does not need changes, see my previous comments.

> I made some other changes, though, and AdminControllerSpec.scala passed all tests, but as you mentioned, it's only testing the users table.

Correct, I believe that's the only table available right now.

> That takes the first item from DataExplorerTestModule.scala, right?

Correct.

> So all the tests here run only on the users table, right? To test uuid_table, int_table, etc, I could do something like this:

That's one way to handle it,, like you mention, it could lead to repetitive code, while it is ideal to avoid it, some repetition isn't a big deal in such a small project.

> Else modify the existing CRUD tests so they run once for each table?

That's what I'd try.

**Comment by nickcoast** [comment]
I was also thinking SERIAL would be the easiest one to implement and also the most common. So I put that and BIGSERIAL in.

For the UUID vs SERIAL issue in QueryBuilder.create, I think the following might work.
I didn't change the loop at all. Instead of omitting the SERIAL id from queries to produce default, we can just set DEFAULT inside the QueryBuilder

Tests I've written so far have passed.

If I want to test this in my other project right away, would it be hard for me to change the webapp template so that it uses my version of the webapp-utils? (Sorry, I'm very new to Scala/Java)

Thanks!



```

    def create(tableName: String, body: Map[String, String], primaryKeyField: String, primaryKeyType: String)(implicit
      conn: Connection
  ): Unit = {
    val sql = QueryBuilder.create(tableName, body, primaryKeyField, primaryKeyType)
    val preparedStatement = conn.prepareStatement(sql)

    if(primaryKeyType == "UUID")  preparedStatement.setObject(1, UUID.randomUUID())
    // TODO: If can figure out how to set DEFAULT here, then won't need to pass primaryKeyType into QueryBuilder.create
    // eg. NULL works in MySQL to generate default value, but not Postgres unfortunately
    // else preparedStatement.setNull(1, java.sql.Types.NULL) // would probably work for MySQL
    // Or if this worked: preparedStatement.setDefault(1, java.sql.Types.DEFAULT) // but no such type as DEFAULT
    // Want to replicate this query: INSERT INTO test_serial (id) VALUES(DEFAULT)

    // Instead for now send primaryKeyType to QueryBuilder.create, where it handles this and sets id = DEFAULT
    // instead of using ? parameter
    // no need to change loop below because Primary key is handled

    for (i <- 2 to body.size + 1) {
      val value = body(body.keys.toList(i - 2))
      preparedStatement.setObject(i, value)
    }
    val _ = preparedStatement.executeUpdate()
  }



  def create(tableName: String, body: Map[String, String], primaryKeyField: String, primaryKeyType: String = "UUID"): String = {
    val sqlFields = new mutable.StringBuilder(primaryKeyField)
    // val sqlValues = new mutable.StringBuilder("?")
    // primaryKeyType necessary because can't pass Postgres DEFAULT to preparedStatement value using scala AFAIK
    val sqlValues = primaryKeyType match {
      case "UUID" => new mutable.StringBuilder("?")
      case _ => new mutable.StringBuilder("DEFAULT") 
    }
    for ((key, _) <- body) {
      sqlFields.append(s", $key")
      sqlValues.append(s", ?")
    }

    s"""
      |INSERT INTO $tableName
      |  ($sqlFields)
      |VALUES (
      |  ${sqlValues.toString()}
      |)
      |""".stripMargin
  }



```

**Comment by AlexITC** [comment]
> If I want to test this in my other project right away, would it be hard for me to change the webapp template so that it uses my version of the webapp-utils? (Sorry, I'm very new to Scala/Java)

Run `sbt +publishLocal` which will publish your updated version to your local repository, then, set such version at [build.sbt](https://github.com/wiringbits/scala-webapp-template/blob/master/build.sbt) (this piece `val webappUtils = "0.5.14"`), if you have an opened sbt session, it needs to be reloaded to pick such changes, if you use intellij, restart it.

I'll check your code later.

**Comment by nickcoast** [comment]
Ok! I rebuilt my webapp template app with my changes from webapp-utils and it works!

But now I'm having a new error with a NULLable timestamp column. Cannot save any record using the admin if that record has a NULL timestamp column, but works if you put in a value.


```
[debug] n.w.w.u.a.c.package$ - Error response while handling a request: ERROR: invalid input syntax for type timestamp with time zone: ""
org.postgresql.util.PSQLException: ERROR: invalid input syntax for type timestamp with time zone: ""
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:167)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:135)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at net.wiringbits.webapp.utils.admin.repositories.daos.DatabaseTablesDAO$.update(DatabaseTablesDAO.scala:225)
	at net.wiringbits.webapp.utils.admin.repositories.DatabaseTablesRepository.$anonfun$update$2(DatabaseTablesRepository.scala:98)
	at net.wiringbits.webapp.utils.admin.repositories.DatabaseTablesRepository.$anonfun$update$2$adapted(DatabaseTablesRepository.scala:83)
	at play.api.db.DefaultDatabase.$anonfun$withTransaction$1(Databases.scala:189)
	at play.api.db.DefaultDatabase.withConnection(Databases.scala:180)
	at play.api.db.DefaultDatabase.withTransaction(Databases.scala:187)
	at net.wiringbits.webapp.utils.admin.repositories.DatabaseTablesRepository.$anonfun$update$1(DatabaseTablesRepository.scala:83)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
org.postgresql.util.PSQLException: ERROR: invalid input syntax for type timestamp with time zone: ""
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:167)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:135)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at net.wiringbits.webapp.utils.admin.repositories.daos.DatabaseTablesDAO$.update(DatabaseTablesDAO.scala:225)
```

Perhaps there's some way to handle empty strings as `NULL`s for non-string NULLable columns?


But the SERIAL primary key working is great, so I'm happy about that. Thanks for all your help. I will push my changes to my Github soon and I can submit a pull request if you want. I might want to clean up some stuff a bit first, though.

**Comment by AlexITC** [comment]
> Ok! I rebuilt my webapp template app with my changes from webapp-utils and it works!

Great!

> But now I'm having a new error with a NULLable timestamp column. Cannot save any record using the admin if that record has a NULL timestamp column, but works if you put in a value.

This must be a bug in our existing implementation, apparently, we are sending an empty string (`""`) instead of `null` to the database.

If I remember correctly, we have some technical debt related which prevents backend from differentiating when a value isn't filled vs the case when an empty string was used.
